acceptable:
  recommended:
    - alphabet
    - complete
    - community-evaluation
  dependencies:
    - clear
    - natural
    - church-leader-check
accuracy-check:
  recommended:
    - language-community-check
    - other-methods
    - guidelines-accurate
  dependencies:
    - church-leader-check
    - guidelines-accurate
    - important-term-check
alignment-tool:
  recommended:
    - vol2-things-to-check
  dependencies:
    - vol2-steps
    - guidelines-accurate
alphabet:
  recommended:
    - spelling
  dependencies:
    - acceptable
    - translate-alphabet
    - formatting
authority-process:
  recommended:
    - peer-check
  dependencies:
    - goal-checking
church-leader-check:
  recommended:
    - accuracy-check
    - good
  dependencies:
    - trans-note-check
clear:
  recommended:
    - acceptable
    - natural
    - guidelines-clear
    - language-community-check
  dependencies:
    - other-methods
community-evaluation:
  recommended:
    - church-leader-check
    - self-assessment
    - good
  dependencies:
    - language-community-check
    - other-methods
    - writing-decisions
    - acceptable
complete:
  recommended:
    - self-assessment
    - good
    - verses
  dependencies:
    - punctuation
formatting:
  recommended:
    - alphabet
    - spelling
    - punctuation
  dependencies:
    - vol2-things-to-check
goal-checking:
  recommended:
    - intro-checking
    - authority-process
  dependencies:
    - intro-check
    - intro-checking
good:
  recommended:
    - self-assessment
  dependencies:
    - complete
    - community-evaluation
headings:
  recommended:
    - community-evaluation
    - publishing
  dependencies:
    - acceptable
    - punctuation
    - verses
important-term-check:
  recommended:
    - accuracy-check
    - trans-note-check
  dependencies:
    - peer-check
    - team-oral-chunk-check
intro-check:
  recommended:
    - goal-checking
  dependencies:
    - intro-checking
intro-checking:
  recommended:
    - intro-check
  dependencies:
    - translate-manual
language-community-check:
  recommended:
    - natural
    - other-methods
    - writing-decisions
    - community-evaluation
  dependencies:
    - accuracy-check
level3-approval:
  recommended:
    - formatting
  dependencies:
    - level3-questions
level3-questions:
  recommended:
    - accuracy-check
    - level3-approval
    - self-assessment
  dependencies:
    - vol2-things-to-check
natural:
  recommended:
    - acceptable
    - guidelines-natural
    - language-community-check
  dependencies:
    - alphabet
    - clear
other-methods:
  recommended:
    - writing-decisions
    - community-evaluation
    - clear
  dependencies:
    - language-community-check
peer-check:
  recommended:
    - team-oral-chunk-check
  dependencies:
    - first-draft
publishing:
  recommended:
    - vol2-backtranslation
  dependencies:
    - headings
punctuation:
  recommended:
    - verses
    - complete
  dependencies:
    - spelling
    - translate-alphabet
    - alphabet
self-assessment:
  recommended:
    - good
    - accuracy-check
    - language-community-check
    - clear
    - natural
    - level3-questions
  dependencies:
    - complete
    - church-leader-check
    - alignment-tool
spelling:
  recommended:
    - punctuation
  dependencies:
    - acceptable
    - translate-alphabet
    - alphabet
team-oral-chunk-check:
  recommended:
    - important-term-check
  dependencies:
    - peer-check
trans-note-check:
  recommended:
    - church-leader-check
  dependencies:
    - important-term-check
verses:
  recommended:
    - headings
  dependencies:
    - spelling
    - punctuation
    - alphabet
    - complete
vol2-backtranslation:
  recommended:
    - vol2-backtranslation-purpose
  dependencies:
    - publishing
    - vol2-steps
vol2-backtranslation-guidelines:
  recommended:
    - vol2-things-to-check
  dependencies:
    - vol2-backtranslation-written
vol2-backtranslation-kinds:
  recommended:
    - vol2-backtranslation-written
  dependencies:
    - vol2-backtranslation-who
vol2-backtranslation-purpose:
  recommended:
    - vol2-backtranslation-who
  dependencies:
    - vol2-backtranslation
vol2-backtranslation-who:
  recommended:
    - vol2-backtranslation-kinds
  dependencies:
    - vol2-backtranslation-purpose
vol2-backtranslation-written:
  recommended:
    - vol2-backtranslation-guidelines
  dependencies:
    - vol2-backtranslation-kinds
vol2-steps:
  recommended:
    - alignment-tool
    - vol2-things-to-check
  dependencies:
    - good
vol2-things-to-check:
  recommended:
    - level3-questions
  dependencies:
    - alignment-tool
